version: 0.2

phases:
  build:
    commands:
      - echo Kwon Pg build...
      - chmod +x ./gradlew
      - ./gradlew build

artifacts:
  files:
    - appspec.yml
    - build/libs/*.jar
  discard-paths: yes
  
cache:
  paths:
    - '/root/.gradle/caches/**/*'